### ISSUE TITLE
Works on box; multiple folder sync?

### ISSUE THREAD

**Issue by darlac** [cjnaz/rclonesync-V2#20]
Hi there, 
just wanted to confirm that the sync works with box cloud service - tested with both arch and debian. 
question: I want to sync 3 different folders - how can I do it in parallel? rclonysync_LOCK prevents that

**Comment by cjnaz** [comment]
The reason I put the lock system in place is to prevent corruption from starting another sync of the same targetsize while a prior big/long sync is still in progress.   Consider editing out the lock code at the bottom of the script, but beware... files can be deleted or replicated if concurrent runs of the same trees are running.

**Comment by cjnaz** [comment]
Thanks for the box feedback.

**Comment by darlac** [comment]
> The reason I put the lock system in place is to prevent corruption from starting another sync of the same targets while a prior big/long sync is still in progress. Consider editing out the lock code at the bottom of the script, but beware... files can be deleted or replicated if concurrent runs of the same trees are running.

HI, thanks for the prompt response - I thought that running different folders (not a duplicate instance of the same sync) would be fine, but it is not - 
should I try to put the lock file in another folder (so there is no interaction)?

**Comment by cjnaz** [comment]
There won't be a conflict if there is no overlap in folders.  The lock filename could be updated to include the path1/2 string's, ad an enhancement.  In the mean time just edit out the lock mechanism.  Should be a simple edit.

**Comment by darlac** [comment]
Yep, I just updated the lock filename and works fine!

**Comment by cjnaz** [comment]
I'll leave this open as an enhancement.

**Comment by cjnaz** [comment]
Updated the lock filename in v2.7.  Thanks.
