### ISSUE TITLE
Use config file in listremotes

### ISSUE THREAD

**Issue by JasperJuergensen** [cjnaz/rclonesync-V2#21]
https://github.com/cjnaz/rclonesync-V2/blob/ae25e491f5d69f8e4f2b7a42adc8388e3156b3d3/rclonesync.py#L661

When getting the remotes from rclone via the `rclone listremotes` command in line 661, the config file path is not used. 

A corrected variant would be `clouds = subprocess.check_output([rclone, "listremotes", "--config", rcconfig])`.

**Comment by cjnaz** [comment]
Thanks.  Corrected in v2.7a.
