### ISSUE TITLE
Can you add a basic installation guide + cron job guide to the wiki / readme?

### ISSUE THREAD

**Issue by recklessnl** [cjnaz/rclonesync-V2#30]
This looks like a great tool, exactly what I'm looking for - I'd like to start using this to backup local files on a Linux server to either dropbox or Google Drive, but I'm not sure how to install it properly and run the cron-job properly. Any tips or a small installation guide would be helpful and much appreciated.

**Comment by cjnaz** [comment]
Added to V2.8 README.md
