### ISSUE TITLE
Banner and success are reported as warnings

### ISSUE THREAD

**Issue by iainhallam** [cjnaz/rclonesync-V2#31]
The comment on the default logging level in rclonesync.py says "Log only unusual events", but the banner, sync notice, and report of successful run are all tagged as warnings, when you'd hope they'd be the norm. This means that when run from cron, there will always be output on success, hence an email to the running user.

Can these normal events be tagged as info rather than warning, so that they will only be shown when running in verbose mode, please?

**Comment by cjnaz** [comment]
Changed in V2.8.  Silent now unless file conflict warnings, or --verbose.
