### ISSUE TITLE
Prior lock file in place, aborting.  Try running rclonesync again.

### ISSUE THREAD

**Issue by MuerteInHell** [cjnaz/rclonesync-V2#4]
I'm encountering following issue:

Tried to run  ./rclonesync.py "GDrive":/test /data --first-sync --dry-run
Interrupted this with ctrl+c because it seemed to work as intended.

When trying to run it again, it keeps saying:
Prior lock file in place, aborting.  Try running rclonesync again.

I have no rclone related processes running. How do I get rid of this lock file?

**Comment by cjnaz** [comment]
Hi.  Please see the README.md Lock file bullet.
