### ISSUE TITLE
logging?

### ISSUE THREAD

**Issue by tulakalbeyo** [cjnaz/rclonesync-V2#40]
awesome python script!! but...
i have to jump through too many hoops to get **rclonesync** to output a .log file to the desktop.
any chance we can get a simple, _internal_ `--logs` option?

thanks!

**Comment by cjnaz** [comment]
Hello, and thanks.  
What's the problem with using output redirection?  `py rclonesync.py ... >> "C:\Users\<your username>\Desktop\logfile.log" 2>&1` ?  The python logger writes to stderr, and the `2>&1` redirects the stderr stream to the file.  This works the same on Windows 10 and Linux.

**Comment by tulakalbeyo** [comment]
oh, this is _**way**_ easier than how i was doing it!! _thanks a lot!!_ :grin:
hopefully the _internal_ `--logs` option will still be implemented, as it will just be neater to write shell scripts with it.
again, thanks! :relaxed:

**Comment by cjnaz** [comment]
I'll leave this open for others to comment

**Comment by cjnaz** [comment]
No discussion on this one, so I'll close it for now.
