### ISSUE TITLE
Adding Support for Symlinks

### ISSUE THREAD

**Issue by coletonodonnell** [cjnaz/rclonesync-V2#41]
I really need bidirectional sync, but my setup relies heavily on symlinks. Would it be possible to include a symlink follow modifier to the script similar to rsync?

`./rclonesync.py /path/ /path/ -whatevercommands -L`

Then it would allow it to follow symlinks.

**Comment by cjnaz** [comment]
Checkout the `--rclone-args` switch.  Put this switch as the last switch on your command line and follow it the the `-L` switch which will get passed to rclone.  Viola, symlinks are followed.  Please close this issue if all is well.  Recognize that it's rclone that is doing the work here, so try to distinguish any issues between rclone and rlconesync.

```
$ rclonesync.py localsyncroot Remote:  --rclone-args -L 
```

**Comment by coletonodonnell** [comment]
Oh, makes sense must've missed that part...

Thank you for that, I will close this.
