### ISSUE TITLE
lock file

### ISSUE THREAD

**Issue by youcanf** [cjnaz/rclonesync-V2#43]
Thanks for the great tool. I have been able to use it without a problem for a long while, until now I am having the following error:

rclonesync.py ~/GoogleDrive/ remote:
2020-03-16 17:24:08,025:  Timed out waiting for lock file to be cleared: </tmp/rclonesync_LOCK__home_GoogleDrive_remote_>
2020-03-16 17:24:08,026:  ***** Prior lock file in place, aborting.  Try running rclonesync again. *****

I have tried --first-sync and --dry-run, which also end up with this error. And I can't find this lock file either. Do you know what could be the possible cause?

**Comment by cjnaz** [comment]
Hi.  Thanks.
The lock file isn't at /tmp/rclonesync_LOCK__home_GoogleDrive_remote_ ???
If so, delete it and do a --first-sync again.

**Comment by youcanf** [comment]
Never mind! I didn't realize that is a valid directory. 
Thanks for your quick response!
