### ISSUE TITLE
Multiple Duplication of files that appear the same...

### ISSUE THREAD

**Issue by domOrielton** [cjnaz/rclonesync-V2#47]
Not sure what has happened here but rclonesync-v2 seems to be duplicating files when it does the sync. Below is an example folder but it did this for hundreds of files across many folders - I've attached an example listing with a shortened version below.
[file_listing.txt](https://github.com/cjnaz/rclonesync-V2/files/4446746/file_listing.txt)

uid@computer:~/Dropbox/Documents/Useful$ ls -la --time-style=full-iso 
total 872
208986 2016-10-31 17:26:02.414733000 +0000 100-blocks-pdf.pdf_Path1_Path1
208986 2016-10-31 17:26:02.000000000 +0000 100-blocks-pdf.pdf_Path1_Path2
208986 2016-10-31 17:26:02.414733500 +0000 100-blocks-pdf.pdf_Path2_Path1
208986 2016-10-31 17:26:02.414733500 +0000 100-blocks-pdf.pdf_Path2_Path2

The folder is a Dropbox folder if that makes a difference, and would have been monitored by the Dropbox app at the time rolesync-V2 was running.

My filters file is similar to the default one provided with a few dropbox additions.
[Filters.txt](https://github.com/cjnaz/rclonesync-V2/files/4446752/Filters.txt)

Unfortunately the log has been overwritten so I can't upload that but the command/parameters used are below 

rclonesync.py /home/computer/Dropbox/ remote:/my-dropbox/ --filters-file Filters --verbose > rclonesync.log 2>&1

Not sure if anyone else has come across this?

**Comment by cjnaz** [comment]
Hi.  Ouch.  
> ... and would have been monitored by the Dropbox app at the time rolesync-V2 was running.

This is Dropbox's Windows sync app?  If so, I suspect that it and rclonesync are fighting with each other.  I've not tested this scenario.  The `_PathX` suffixed files come up when rclonesync sees a file changed on both sides.  See the README for [UNusual sync checks](https://github.com/cjnaz/rclonesync-V2#unusual-sync-checks).

**Comment by cjnaz** [comment]
I'll close this issue for now, assuming that eliminating the Dropbox app from also syncing solves the problem.  If that's not the problem, feel free to reopen it.
