### ISSUE TITLE
Dropbox still giving modification time error after --rclone-args

### ISSUE THREAD

**Issue by famewolf** [cjnaz/rclonesync-V2#52]
Can you point out where I'm going wrong with this?

/mnt/tank/scripts/rclonesync.py --first-sync -v -f /mnt/tank/homes/famewolf/.rclonesyncwd/Filters Dropbox: /mnt/tank/shared/Cloud/Dropbox/ --rclone-args --koofr-setmtime=false

because I'm still getting:

2020/06/07 19:30:27 ERROR : iMacros/Part2run_error.log: Failed to set modification time: chtimes /mnt/tank/shared/Cloud/Dropbox/iMacros/Part2run_error.log: operation not permitted
2020/06/07 19:30:41 ERROR : Local file system at /mnt/tank/shared/Cloud/Dropbox/: not deleting files as there were IO errors
2020/06/07 19:30:41 ERROR : Local file system at /mnt/tank/shared/Cloud/Dropbox/: not deleting directories as there were IO errors
2020/06/07 19:30:41 ERROR : Attempt 1/3 failed with 2 errors and: not deleting files as there were IO errors
2020/06/07 19:30:42 ERROR : iMacros/Part2run_error.log: Failed to set modification time: chtimes /mnt/tank/shared/Cloud/Dropbox/iMacros/Part2run_error.log: operation not permitted

**Comment by famewolf** [comment]
I should add that the dropbox sync worked several times then noticed this popped up so added the rclone args as per the docs.

**Comment by famewolf** [comment]
I deleted the error log (and a couple of others) it was flagging and the job ran as it should.  Not sure what would have been specific to it and I'll let yall decide whether to close this given there was some sort of error.

**Comment by cjnaz** [comment]
Is it possible that some other app had Part2run_error.log open?  Also, the `--koofr-setmtime` switch is probably not valid with Dropbox.

The date stamps with /'s in them are from rclone, fyi, such as 
```
2020/06/07 19:30:27 ERROR : iMacros/Part2run_error.log: Failed to set modification time: chtimes /mnt/tank/shared/Cloud/Dropbox/iMacros/Part2run_error.log: operation not permitted
```
