### ISSUE TITLE
rclonesync-V3

### ISSUE THREAD

**Issue by luislozoya** [cjnaz/rclonesync-V2#57]
hello I might be doing something wrong but I can't manage to make v3 work 
i use git clone on a new directory and tried the following 

`/home/pi/stuff/scripts/rclonesync-V3/rclonesync rclone:"/googledrive/" /media/pi/AEDAD26EDAD23277/googledrive --first-sync --dry-run --rc-verbose`

and I get this error 

```
  File "/home/pi/stuff/scripts/rclonesync-V3/rclonesync", line 151
    logging.error(print_msg("ERROR", f"Failed loading {path_text} list file <{lsl_file}>"))
```

**Comment by cjnaz** [comment]
What's your Python version?  Known to work on 3.6.8 and later.

**Comment by cjnaz** [comment]
Assuming that `rclone:` is the name of your configured remote then change `rclone:"/googledrive/"` to `rclone:/googledrive/`.

Did this work on V2.10 or V2.11?

**Comment by luislozoya** [comment]
My bad i ran it with the defaults, wich was python 2.7 
I change it to run with 3.6 and everything is fine
thanks
