### ISSUE TITLE
rclone version

### ISSUE THREAD

**Issue by egonza1661** [cjnaz/rclonesync-V2#60]
Please update installing instructions as I had rclone version 1.51 in my system and when I run for the first time I had the following error. 
2020/09/06 12:53:13 Fatal error: unknown flag: --files-from-raw
Error: unknown flag: --files-from-raw
Usage:
  rclone copy source:path dest:path [flags]

Once I installed version 1.53 from rclone.org web page everything worked.
Maybe is not a big deal, but for somebody that doesn't have much experience with linux would be a big help. I spent a couple of hours trying to figure it out.
Thank for a great job.

**Comment by cjnaz** [comment]
Thanks.  Try the Tag version 3.1.  I updated the README to indicate rclone 1.52 minimum and made other improvements.  I am waiting for feedback from another user before posting to Master, but it should be solid.  I'll likely add an rclone min version check before release.
