### ISSUE TITLE
successive rclonesync with google drive are reporting "need to run with --first-sync ... read README.MD"

### ISSUE THREAD

**Issue by lbiaggi** [cjnaz/rclonesync-V2#69]
Hi Chris, rclonesync is amazing, it’s saving my life,

I set up a crontab as you suggested and noticed that without --first-sync, successive runs were failing. Taking a look, I found that if I remove the --check-access security check, it works as expected. My crontab job is defined as
`* / 5 * * * * rclonesync ~ / googledrive drive: --filters-file blacklist.conf --rclone-args --drive-skip-gdocs >> ~ / .log / rclonesync / lbiaggi / runlog 2> & 1` and now everything works as expected.

I'm not sure if it's an issue or a related issue about how rclone handles gdrive.

BTW, Great JOB!

**Comment by cjnaz** [comment]
Have you placed RCLONE_TEST files?  Run with -v.  What's the error message?

**Comment by cjnaz** [comment]
Read up on --check-access

**Comment by cjnaz** [comment]
Can we close this issue?

**Comment by lbiaggi** [comment]
yup
