### ISSUE TITLE
GDrive: rateLimitExceeded

### ISSUE THREAD

**Issue by MuerteInHell** [cjnaz/rclonesync-V2#7]
I've started getting Rate limit exceeded using Google Drive (rclonesync.py V2.1 180729):

ERROR : xxxx/xxxx: error reading destination directory: couldn't list directory: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

The sync does proceed afterwards

**Comment by cjnaz** [comment]
Please see [https://github.com/cjnaz/rclonesync-V2/blob/master/TROUBLESHOOTING.md#reading-rclone-and-rclonesync-logs](url).  If the rclone sync completes with `>>>>> Successful run.  All done.` then you are good to go.  There isn't anything rclonesync can do to prevent the rclone errors, and rclone retries, usually successfully.
