### ISSUE TITLE
Original files deleted when file is changed in both locations

### ISSUE THREAD

**Issue by boldandbusted** [cjnaz/rclonesync-V2#70]
Howdy. I haven't yet created a demonstration case for this but this just happened to me with rclonesyc v3.1:

* Files with the same name were changed in both paths.
* `rclonesync localpath/ gdrive:/remotepath/`
* rclonesync logs show that it was creatig _Path1 and _Path2 files (expected).
* `ls` in localpath/, and, the original file AND the _Path* files are *not* present.
* The _Path* files *are* present in the destination path `gdrive:/remotepath/`

Then, I try to re-run rclonesync so I have the _Path* files in localpath/ , so I can handle them. But, rclonesync runs without error, and the localpath/ is unchanged (no _Path* files copied locally).

Rclone version:
```
$ rclone --version
rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.7
```

Rclonesync version:
```
$ rclonesync --version
rclonesync V3.1 200909
```

Happy to help with more information. Luckily gdrive is versioned. :) Thank you for rclonesync-V2! :)

**Comment by cjnaz** [comment]
Just this weekend I had similar problems with rclone moveto in v1.52.2.  In
my case rclone would not rename the remote file to _path2, and critical
errored out.

Changing to v1.53.3 fixed it.  Give that a try.

I think I'll implement an integrity check for sameness of the two final LSL
files, which would catch the problem you've found.

**Comment by cjnaz** [comment]
Check-Sync feature added to V3.2, enabled by default.  This should catch the rare instance of the two path LSL files getting out of sync.  Also updated the min rclone rev required to v1.53.  

Please give V3.2 with rclone v1.53.x a go and try to replicate the lost file.

**Comment by cjnaz** [comment]
Any news?

**Comment by cjnaz** [comment]
Suspected to be a bug with 1.52.2.

**Comment by boldandbusted** [comment]
I'm sorry I missed the followup @cjnaz wrote. I just tried it with the single file I have (a Keepass database) that often changes in both local and remote - and the original file deletion issue did not recur. (It did make the _Path1 and _Path2 copies as expected.) Thank you! 🥇 💯 🥇
