### ISSUE TITLE
One way sync

### ISSUE THREAD

**Issue by DarrenPIngram** [cjnaz/rclonesync-V2#82]
I couldn't see this in the docs, but is there (or can there be) a way to do a one-way sync only?

Use case; rclone sync itself doesn't clean up well for me in some cases, especially with folder or file renames. 

Want to ensure a 1:1 copy from server A to B *only*.

**Comment by cjnaz** [comment]
Hum...  rclonesync wont do what you want.  Perhaps raise the question on the rlcone forum.  Just curious, what mess does rlcone sync leave?

**Comment by DarrenPIngram** [comment]
Thank you for the verification.
I'm finding at times rclone sync is not deleting directories at destination
(e.g. on rename) even if no errors were reported.

Plus I don't see a "force resync" option. The rclone check may make a list
of files but nothing to act on them -- and resyncing a multi Tb directory
and trying to clean it up "manually" is not a fun task.

**Comment by DarrenPIngram** [comment]
Yes I will prepare something, thanks.
